image: Visual Studio 2017
version: '1.0.2-{build}'

install:
  - choco install nodejs-lts --version=14.16.0
  - ps: pushd
  - ps: mkdir "C:\Program Files (x86)\GnuWin32"
  - cd "C:\Program Files (x86)\GnuWin32"
  # stupid sourceforge
  - ps: wget https://netix.dl.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-dep.zip -OutFile make-dep.zip
  - ps: wget https://deac-fra.dl.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-bin.zip -OutFile make-bin.zip
  - ps: Expand-Archive make-dep.zip -DestinationPath .
  - ps: Expand-Archive make-bin.zip -DestinationPath .
  - ps: popd

before_build:
  - ps: |
      $env:PATH = "C:\Program Files (x86)\GnuWin32\bin;" + $env:PATH
      make electron-develop 2>$null

build_script:
  - ps: |
      $env:PATH = "C:\Program Files (x86)\GnuWin32\bin;" + $env:PATH
      make electron-build 2>$null

after_build:
  - ps: |
      cd dist
      Get-ChildItem -Filter *.exe | Rename-Item -NewName { $_.name -replace 'Abitikku-(.*?)-(.*)\+.*', 'Abitikku-$1-$2.exe' }

artifacts:
  - path: dist/*.exe
