image: Visual Studio 2015
version: '1.0.2-{build}'

install:
  #- choco install nodejs-lts --version=14.16.0
  - choco install gnuwin32-coreutils.install

before_build:
  - ps: |
      $env:PATH = $env:PATH + "C:\Program Files (x86)\GnuWin32\bin"
      make electron-develop

build_script:
  - ps: |
      $env:PATH = $env:PATH + "C:\Program Files (x86)\GnuWin32\bin"
      make electron-build

after_build:
  - ps: |
      cd dist
      Get-ChildItem -Filter *.exe | Rename-Item -NewName { $_.name -replace 'Abitikku-(.*?)-(.*)\+.*', 'Abitikku-$1-$2.exe' }

artifacts:
  - path: dist/*.exe
