image: Visual Studio 2015
version: '1.0.2-{build}'

install:
  - choco install nodejs-lts --version=14.16.0

before_build:
  - make electron-develop

build_script:
  - make electron-build

after_build:
  - ps: |
      cd dist
      Get-ChildItem -Filter *.exe | Rename-Item -NewName { $_.name -replace 'Abitikku-(.*?)-(.*)\+.*', 'Abitikku-$1-$2.exe' }

artifacts:
  - path: dist/*.exe

deploy:
  - provider: GitHub
    artifact: /*.exe/
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true