image: Visual Studio 2015
version: '1.0.2-{build}'

install:
  - choco install nodejs-lts --version=14.16.0
  - mkdir make_install
  - cd make_install
  # stupid sourceforge
  - ps: wget https://jztkft.dl.sourceforge.net/project/gnuwin32/make/3.81/make-3.81.exe -OutFile make-3.81.exe
  - make-3.81.exe /S

before_build:
  - ps: |
      $env:PATH = "C:\Program Files (x86)\GnuWin32\bin;" + $env:PATH
      make electron-develop

build_script:
  - ps: |
      $env:PATH = "C:\Program Files (x86)\GnuWin32\bin;" + $env:PATH
      make electron-build

after_build:
  - ps: |
      cd dist
      Get-ChildItem -Filter *.exe | Rename-Item -NewName { $_.name -replace 'Abitikku-(.*?)-(.*)\+.*', 'Abitikku-$1-$2.exe' }

artifacts:
  - path: dist/*.exe
