image: Visual Studio 2017
version: '1.0.2-{build}'

install:
  - ps: |
      # choco install nodejs-lts --version=14.16.0
      pushd
      cd $(mkdir "C:\Program Files (x86)\GnuWin32")
      wget https://netix.dl.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-dep.zip -OutFile make-dep.zip
      wget https://deac-fra.dl.sourceforge.net/project/gnuwin32/make/3.81/make-3.81-bin.zip -OutFile make-bin.zip
      Expand-Archive make-dep.zip -DestinationPath .
      Expand-Archive make-bin.zip -DestinationPath .
      popd

# For some reason random messages end up as stderr so we just disable everything
before_build:
  - ps: |
      Write-Error test *>$null | Out-Null
      # $env:PATH = "C:\Program Files (x86)\GnuWin32\bin;" + $env:PATH
      # make electron-develop *>$null | Out-Null

build_script:
  - ps: |
      $env:PATH = "C:\Program Files (x86)\GnuWin32\bin;" + $env:PATH
      make electron-build 2>$null

after_build:
  - ps: |
      cd dist
      Get-ChildItem -Filter *.exe | Rename-Item -NewName { $_.name -replace 'Abitikku-(.*?)-(.*)\+.*', 'Abitikku-$1-$2.exe' }

artifacts:
  - path: dist/*.exe
